name: GITHUB_OUTPUT # p.54 （GITHUB_OUTPUT環境変数） なお、p.55には（GITHUB_ENV環境変数）の使い方が記載されているが、非推奨とのこと。
on: push
jobs:
  share:
    runs-on: ubuntu-latest
    steps:
      - id: source # ステップIDを設定
        run: echo "result=Hello" >> "${GITHUB_OUTPUT}" # GITHUB_OUTPUTへ書き出し echo "<key>=<value>"
      - env:
          RESULT: ${{ steps.source.outputs.result }} # stepsコンテキストから参照 steps.<step-id>.outputs.<key>
        run: echo "${RESULT}"